name: install-test
run-name: NPM Install and Test
on:
  pull_request:
    branches: [ master, develop ]
jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node Env
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout Repo Code
        uses: actions/checkout@v5.0.0
      - run: npm i
      - run: npm test