name: Publish to Github NPM
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nordic96'
      - name: Install dependencies and build 🔧
        run: npm i && npm run build
      - name: Commit to Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am new_version
          git push
      - name: Version Patch
        run: npm version patch
      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}